#define INIT_SCREEN 1
#define LOGIN_SCREEN 11
#define REGISTER_SCREEN 12

#define MAIN_MENU_SCREEN 2
#define FIND_GAME_SCREEN 21
#define SET_GAME_PARAM 22
#define CHANGE_GAME_PARAM 221

#define INVITATIONS_SCREEN 23
#define CLASSEMENT_SCREEN 24
#define LIST_FRIENDS_SCREEN 25
#define HISTORIQUE_SCREEN 26
#define CHAT_SCREEN 27
#define ROOM_SCREEN 28
#define SET_LOMBRIC_TEAM_SCREEN 29

#define INVIT_FRIEND_TO_GAME_SCREEN 30
#define INVIT_NEW_FRIEND_SCREEN 31
#define FRIENDS_SCREEN 32


#define GAME_SCREEN 80

#define WARNING_SCREEN 5
#define WAITING_SCREEN 70
#define WARNING_DECONNECTION_DCREEN 60
#define WARNING_DEL_FRIEND_SCREEN 61
#define LEAVE -1
