#define INIT_SCREEN 1
#define LOGIN_SCREEN 11
#define REGISTER_SCREEN 12

#define MAIN_MENU_SCREEN 2
#define FIND_GAME_SCREEN 21
#define SET_GAME_PARAM 22
#define CHANGE_GAME_PARAM 221

#define INVITATIONS_SCREEN 23
#define CLASSEMENT_SCREEN 24
#define LIST_FRIENDS_SCREEN 25
#define HISTORIQUE_SCREEN 26
#define CHAT_SCREEN 27
#define ROOM_SCREEN 28
#define SET_LOMBRIC_TEAM_SCREEN 29

#define INVIT_FRIEND_TO_GAME_SCREEN 30
#define INVIT_NEW_FRIEND_SCREEN 31
#define FRIENDS_SCREEN 32
#define HISTORY_REQUEST_SCREEN 71

#define DETAILS_SCREEN 81


#define GAME_SCREEN 80

#define END_SCREEN 90

#define WARNING_SCREEN 5
#define WAITING_SCREEN 70
#define WARNING_DECONNECTION_SCREEN 60
#define WARNING_DEL_FRIEND_SCREEN 61
#define WARNING_EMPTY_HISTORIC_SCREEN 53
#define WARNING_EMPTY_RANKE_SCREEN 54
#define WARNING_WRONG_PSEUDO_SCREEN 55
#define WARNING_FIRST_COME_WRONG_PARAMETERS_SCREEN 56
#define WARNING_SECOND_COME_WRONG_PARAMETERS_SCREEN 561
#define WARNING_FIRST_COME_WRONG_FIRST_PARA_SCREEN 57
#define WARNING_SECOND_COME_WRONG_FIRST_PARA_SCREEN 571
#define WARNING_FIRST_COME_WROND_SECOND_PARA_SCREEN 58
#define WARNING_SECOND_COME_WROND_SECOND_PARA_SCREEN 581
#define WARNING_FIRST_COME_WRONG_THIRD_PARA_SCREEN 59
#define WARNING_SECOND_COME_WRONG_THIRD_PARA_SCREEN 591
#define WARNING_FIRST_COME_WRONG_FOUR_PARA_SCREEN 63
#define WARNING_SECOND_COME_WRONG_FOUR_PARA_SCREEN 631
#define WARNING_PSEUDO_ALREADY_EXIST_SCREEN 62
#define WARNING_WRONG_DATA_IN_LOGIN_SCREEN 51

#define LEAVE -1
